export const IMAGES = {
  LOGO: require('../assets/images/logo.png'),
  MAP_FRAME: require('../assets/images/map_frame.png'),
  PAGE_ONE_INDICATOR: require('../assets/images/page_one_indicator.png'),
  PAGE_TWO_INDICATOR: require('../assets/images/page_two_indicator.png'),
  PAGE_TWO_FRAME: require('../assets/images/page_two_frame.png'),
  ICON_LOCATION: require('../assets/images/icon_location.png'),
  ICON_MEDICINE: require('../assets/images/icon_medicine.png'),
  ICON_NOTIFICATION: require('../assets/images/icon_notification.png'),
  ICON_PHARMACY: require('../assets/images/icon_pharmacy.png'),
  ICON_MENU: require('../assets/images/icon_menu.png'),
  PUBLICITY_TEST: require('../assets/images/publicity_test.png'),
  PROFILE: require('../assets/images/profile.png'),
  TABLER_X: require('../assets/images/tabler_x.png'),
  ICON_PHARMACY_2: require('../assets/images/icon_pharmacy_2.png'),
  ICON_SEARCH: require('../assets/images/icon_search.png'),
  ICON_FILTER: require('../assets/images/icon_filter.png'),
  ICON_CHEVRON: require('../assets/images/icon_chevron.png'),
  ICON_CITY: require('../assets/images/icon_city.png'),
  ICON_SECTOR: require('../assets/images/icon_sector.png'),
  ICON_REGION: require('../assets/images/icon_region.png'),
  LINE: require('../assets/images/line.png'),
};
